### PR TITLE
set NOT_CRAN=true

### PR DESCRIPTION
**Pull request by pawelru**

### CODE REVIEW

**Comment by pawelru** [comment]
Just an evidence of the outcome.

here: 
image

a different randomly selected PR:
image

**Comment by shajoezhu** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by shajoezhu** [comment]
hi @pawelru , can you type in "I have read the CLA Document and I hereby sign the CLA"please. thanks

**Comment by pawelru** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by shajoezhu — APPROVED** [review]
lgtm! thanks @pawelru

**Pull request merged**
