### PR TITLE
fix listing pagination test that relied on colgap pagination bug

### PR DESCRIPTION
**Pull request by gmbecker**

### CODE REVIEW

**Comment by gmbecker** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by shajoezhu** [comment]
480 runs  237 ✅ 243 💤 0 ❌

skipped ... lets check what happened if this is ok

**Review by shajoezhu — CHANGES_REQUESTED** [review]
formatters version will be >= 0.5.7.9000

**Comment by shajoezhu** [comment]
> 480 runs  237 ✅ 243 💤 0 ❌
> 
> skipped ... lets check what happened if this is ok

hi @pawelru , I was wondering if anything we can do to not skip these tests

**Comment by Melkiades** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by shajoezhu** [comment]
hi @pawelru , we seem to have a lot of tests skipped again? I was wondering do you have any clue why? any suggestion that where we can fix these?

https://github.com/insightsengineering/scda.test/pull/139#issuecomment-2138610231

**Review by Melkiades — APPROVED** [review]
all good for me !!

**Pull request merged**
