### PR TITLE
check for higher level ns PR

### PR DESCRIPTION
**Pull request by gmbecker**
automatic check for upstream rtables PR

### CODE REVIEW

**Comment by gmbecker** [comment]
@shajoezhu @Melkiades these failures are unrelated to my PR as far as I can see (especially since the same error is happening in listings and this is a pure rtables change...)

**Comment by shajoezhu** [comment]
hi @gmbecker , thanks for flagging this. this is relating to changes in PR https://github.com/insightsengineering/scda.test/pull/140

@gmbecker , I was wondering if you had refesh your test data for this as well? 

@zdz2101 and @edelarua can you take a look at this please?

**Comment by shajoezhu** [comment]
hi @gmbecker , I think this should be resolved once we have pharmaverseadam package updated by https://github.com/pharmaverse/pharmaverseadam/pull/61

**Comment by zdz2101** [comment]
> hi @gmbecker , I think this should be resolved once we have pharmaverseadam package updated by [pharmaverse/pharmaverseadam#61](https://github.com/pharmaverse/pharmaverseadam/pull/61)

precisely, my mistake for having merged mine in before the package made their update

**Comment by gmbecker** [comment]
clean check @shajoezhu

**Review by shajoezhu — APPROVED** [review]
lgtm! thanks @gmbecker

**Pull request merged**
